logging:
  level:
    ROOT: INFO
    tech.jhipster: INFO
    by.homesite.gator: INFO
spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: 'jdbc:sqlite:c:/work/java/joplin-forwarder/joplinforwarder.db'
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        maximumPoolSize: 1
        maximum-pool-size: 1
        minimum-idle: 1
        minimumIdle: 1
    tomcat:
      max-active: 1
      initial-size: 1
      max-idle: 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.sqlite.hibernate.dialect.SQLiteDialect
  mail:
    host: localhost
    port: '2525'
  thymeleaf:
    cache: false
server:
  port: 8585

# App Properties
application:
  general:
    baseUrl: 'http://localhost:8585/'
  mail:
    from: support-joplin@homesite.by
    baseUrl: 'http://localhost:4200/'
  upload:
    local-path: 'c:/work/java/joplin-forwarder/'
    upload-dir: uploads
  cors:
    allowed-origins: 'http://localhost:4200'
