logging:
  level:
    ROOT: INFO
    tech.jhipster: INFO
    by.homesite.gator: INFO
spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: 'jdbc:sqlite:c:/work/java/joplin-forwarder/joplinforwarder.db'
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.sqlite.hibernate.dialect.SQLiteDialect
  mail:
    host: localhost
    port: '2525'
  thymeleaf:
    cache: false
server:
  port: 8080

# App Properties
application:
  general:
    baseUrl: 'http://localhost:8080/'
  mail:
    from: support-joplin@homesite.by
    baseUrl: 'http://localhost:4200/'
  upload:
    local-path: 'c:/work/java/joplin-forwarder/'
    upload-dir: uploads
  cors:
    allowed-origins: 'http://localhost:4200'
