logging:
  level:
    ROOT: INFO
    tech.jhipster: INFO
    by.homesite.gator: INFO
spring:
  datasource:
    url: 'jdbc:sqlite:/opt/joplin-forwarder/joplinforwarder.db'
    hikari:
      poolName: Hikari
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
     properties:
       hibernate:
         dialect: org.sqlite.hibernate.dialect.SQLiteDialect
         jdbc:
           lob:
             non_contextual_creation: true
  mail:
    host: smtp.gmail.com
    port: '587'
#    username: <login user to smtp server>
#    password: <login password to smtp server>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    cache: true
  devtools:
    add-properties: false
server:
  port: 9898
  shutdown: graceful # see https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-graceful-shutdown
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

# App Properties
application:
  general:
    baseUrl: 'http://api-forwarder.homesite.by/'
    crawler-schedulers: true
    rate-schedulers: false
  mail:
    from: support-joplin@homesite.by
    baseUrl: 'http://forwarder.homesite.by/'
  upload:
    local-path: '/opt/joplin-forwarder/'
    upload-dir: uploads
  cors:
    allowed-origins: 'http://api-forwarder.homesite.by/'
