logging:
  level:
    ROOT: INFO
    by:
      homesite:
        joplinforwarder: INFO
spring:
  application:
    name: forwader-server
  profiles:
    active: dev
    group:
      dev: 'dev, api-docs'
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    flyway:
      locations: 'classpath:/db/migration'
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: 'classpath:/templates/'
    suffix: '.html'

# App Properties
application:
  general:
    jwtSecret: joplinforwarderSecretKey
    jwtExpirationMs: 86400000
    default_lang: en
  cors:
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Link,X-Total-Count,X-joplin-alert,X-joplin-error,X-joplin-params'
    allow-credentials: true
    max-age: '1800'
