logging:
  level:
    ROOT: INFO
    by.homesite.joplinforwarder: INFO
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/joplin?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: joplin
    password: jopjopjop
    hikari:
      poolName: Hikari
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
     database: MYSQL
     show-sql: false
     properties:
       hibernate.id.new_generator_mappings: true
       hibernate.connection.provider_disables_autocommit: true
       hibernate.cache.use_second_level_cache: false
       hibernate.cache.use_query_cache: false
       hibernate.generate_statistics: false
       hibernate:
         jdbc:
           lob:
             non_contextual_creation: true
  mail:
    host: localhost
    protocol: smtp
  thymeleaf:
    cache: true
  devtools:
    add-properties: false
server:
  port: 8383
  shutdown: graceful # see https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-graceful-shutdown
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024

# App Properties
application:
  general:
    baseUrl: 'https://fw.homesite.by/'
    crawler-schedulers: true
  mail:
    from: support-joplin@homesite.by
    baseUrl: 'https://fw.homesite.by/'
  upload:
    local-path: '/mnt/vol1/www/joplin/data/'
    upload-dir: uploads
  cors:
    allowed-origins: 'https://fw.homesite.by/'
